# Generated by Django 4.2.7 on 2023-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='image',
            field=models.ImageField(height_field=500, upload_to='', width_field=400),
        ),
    ]
