# Generated by Django 4.2.7 on 2023-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_episodes_slug_alter_episodes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
