# Generated by Django 4.2.7 on 2023-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_episodes_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodes',
            options={'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='episodes',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
