# Generated by Django 4.2.7 on 2023-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_episodes_options_alter_tags_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='home.tags'),
        ),
    ]
