# Generated by Django 4.2.7 on 2024-04-04 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_author_remove_episodes_author_episodes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
