# Generated by Django 4.2.7 on 2024-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_episodes_author_episodes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
