# Generated by Django 4.2.7 on 2024-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_episodes_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodes',
            options={'ordering': ['-time_create'], 'verbose_name_plural': 'Episodes'},
        ),
    ]
